import type { Metadata } from 'next';
import { Inter, JetBrains_Mono } from 'next/font/google';
import './globals.css';

const inter = Inter({
  style: 'normal',
  subsets: ['cyrillic', 'latin'],
  weight: ['400', '500', '600', '700', '900']
});
const jetBrains = JetBrains_Mono({
  style: 'normal',
  subsets: ['cyrillic', 'latin'],
  weight: ['400'],
  variable: '--jet-brains-mono'
});

export const metadata: Metadata = {
  title: 'ScannerBox - сканирование периметра сети',
  description: 'Generated by create next app'
};

export default function RootLayout({
  children
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang='en'>
      <body className={`${inter.className} ${jetBrains.variable} antialiased`}>{children}</body>
    </html>
  );
}
