"""empty message

Revision ID: fdc861c03e40
Revises: 7f9ee758a8a4
Create Date: 2024-11-24 02:01:15.701710

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'fdc861c03e40'
down_revision: Union[str, None] = '7f9ee758a8a4'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint('assets_name_key', 'assets', type_='unique')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_unique_constraint('assets_name_key', 'assets', ['name'])
    # ### end Alembic commands ###
